# Generated by Django 5.2.5 on 2025-11-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_flashsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsale',
            name='product_quantity',
        ),
    ]
