# Generated by Django 5.1.2 on 2026-02-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_city_product_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cities',
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
    ]
