# Generated by Django 5.1.2 on 2026-03-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_aids_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
