# Generated by Django 5.1.2 on 2026-04-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_assigned_at_order_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='block_flat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
