# Generated by Django 5.1.2 on 2026-04-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_block_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='block_flat',
        ),
        migrations.AddField(
            model_name='user',
            name='block_flat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
