# Generated by Django 5.2.5 on 2025-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='is_order_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
