# Generated by Django 5.2.5 on 2025-10-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_usercart_is_order_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
